# Generated by Django 4.2.7 on 2024-07-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('examname', models.CharField(max_length=30)),
                ('examdisp', models.CharField(max_length=50)),
                ('numofquestion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('sem', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Questionpaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('opt1', models.CharField(max_length=100)),
                ('opt2', models.CharField(max_length=100)),
                ('opt3', models.CharField(max_length=100)),
                ('opt4', models.CharField(max_length=100)),
                ('rigthopt', models.CharField(max_length=100)),
                ('nameofexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.exampaper')),
            ],
        ),
    ]
