# Generated by Django 4.2.7 on 2024-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='examdisp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examname',
            field=models.CharField(max_length=50),
        ),
    ]
