# Generated by Django 4.2.7 on 2024-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_student_points_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
